#!/usr/bin/env bash

session=$(find /home/sahilhawal/Code -mindepth 1 -maxdepth 1 -type d | fzf)
[ -z "$session" ] && exit 0

session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2>/dev/null; then
  # Create the first window with nvim
  tmux new-session -s "$session_name" -c "$session" -d "nvim ."

  # Create second window (normal terminal)
  tmux new-window -t "$session_name" -c "$session"

  # Create third window with lazygit
  tmux new-window -t "$session_name" -c "$session" "lazygit"

  # Go back to first window
  tmux select-window -t "$session_name:1"
fi

tmux switch-client -t "$session_name"
